// ------------------------------------------------------------------
// Module: fpga_top
// Description: Basys 3 Hardware Wrapper for Mano Pipeline
// ------------------------------------------------------------------
module fpga_top (
    input  wire        clk,   // 100 MHz board clock (W5)
    input  wire        btnC,  // Center button for Reset (U18)
    input  wire        sw,    // Switch 0 to toggle LED view (V17)
    output reg  [15:0] led    // 16 LEDs for results
);

    wire reset = btnC;

    // CPU Memory Bus
    wire [11:0] inst_addr;
    wire [15:0] inst_data;
    wire [11:0] data_addr;
    wire        data_read_en;
    wire        data_write_en;
    wire [15:0] data_in;
    wire [15:0] data_out;

    // Instantiate Pipeline
    mano_pipeline cpu (
        .clk(clk),
        .reset(reset),
        .inst_addr(inst_addr),
        .inst_data(inst_data),
        .data_addr(data_addr),
        .data_read_en(data_read_en),
        .data_write_en(data_write_en),
        .data_in(data_in),
        .data_out(data_out)
    );

    // Unified Memory mapped to FPGA Block RAM
    reg [15:0] ram [0:4095];

    initial begin
        // Loads the hex code generated by your Python assembler
        $readmemh("program.mem", ram);
    end

    // Memory Read Logic (Combinational)
    assign inst_data = ram[inst_addr];
    assign data_in   = (data_read_en) ? ram[data_addr] : 16'h0000;

    // Memory Write Logic (Synchronous)
    always @(posedge clk) begin
        if (data_write_en) begin
            ram[data_addr] <= data_out;
        end
    end

    // --------------------------------------------------------
    // OUTPUT SNOOPING (Capture Results for LEDs)
    // --------------------------------------------------------
    reg [15:0] final_exp;
    reg [15:0] final_man;

    always @(posedge clk) begin
        if (reset) begin
            final_exp <= 16'b0;
            final_man <= 16'b0;
        end else if (data_write_en) begin
            // Lock the results when the CPU writes to these specific addresses
            if (data_addr == 12'h04D) final_exp <= data_out;
            if (data_addr == 12'h04E) final_man <= data_out;
        end
    end

    // Toggle LED display: Switch OFF = Mantissa, Switch ON = Exponent
    always @(*) begin
        if (sw) led = final_exp;
        else    led = final_man;
    end

endmodule// ------------------------------------------------------------------
// Module: fpga_top
// Description: Basys 3 Hardware Wrapper for Mano Pipeline
// ------------------------------------------------------------------
module fpga_top (
    input  wire        clk,   // 100 MHz board clock (W5)
    input  wire        btnC,  // Center button for Reset (U18)
    input  wire        sw,    // Switch 0 to toggle LED view (V17)
    output reg  [15:0] led    // 16 LEDs for results
);

    wire reset = btnC;

    // CPU Memory Bus
    wire [11:0] inst_addr;
    wire [15:0] inst_data;
    wire [11:0] data_addr;
    wire        data_read_en;
    wire        data_write_en;
    wire [15:0] data_in;
    wire [15:0] data_out;

    // Instantiate Pipeline
    mano_pipeline cpu (
        .clk(clk),
        .reset(reset),
        .inst_addr(inst_addr),
        .inst_data(inst_data),
        .data_addr(data_addr),
        .data_read_en(data_read_en),
        .data_write_en(data_write_en),
        .data_in(data_in),
        .data_out(data_out)
    );

    // Unified Memory mapped to FPGA Block RAM
    reg [15:0] ram [0:4095];

    initial begin
        // Loads the hex code generated by your Python assembler
        $readmemh("program.mem", ram);
    end

    // Memory Read Logic (Combinational)
    assign inst_data = ram[inst_addr];
    assign data_in   = (data_read_en) ? ram[data_addr] : 16'h0000;

    // Memory Write Logic (Synchronous)
    always @(posedge clk) begin
        if (data_write_en) begin
            ram[data_addr] <= data_out;
        end
    end

    // --------------------------------------------------------
    // OUTPUT SNOOPING (Capture Results for LEDs)
    // --------------------------------------------------------
    reg [15:0] final_exp;
    reg [15:0] final_man;

    always @(posedge clk) begin
        if (reset) begin
            final_exp <= 16'b0;
            final_man <= 16'b0;
        end else if (data_write_en) begin
            // Lock the results when the CPU writes to these specific addresses
            if (data_addr == 12'h04D) final_exp <= data_out;
            if (data_addr == 12'h04E) final_man <= data_out;
        end
    end

    // Toggle LED display: Switch OFF = Mantissa, Switch ON = Exponent
    always @(*) begin
        if (sw) led = final_exp;
        else    led = final_man;
    end

endmodule